### ISSUE TITLE
Start an agent on custom network gcp

### ISSUE THREAD

**Issue by mayacdoit** [JetBrains/teamcity-google-agent#12]
Hi,
The agent is able to start on gcp default network, but when change the google cloud "Network" to our own internal subnet, in this case called "staging" the agent fails and not even get created on google cloud console.
Here is the error on teamcity:
Error:
```
com.google.cloud.compute.ComputeException: Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode networkcom.google.cloud.compute.ComputeException: Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network
at com.google.cloud.compute.spi.v1.HttpComputeRpc.translate(HttpComputeRpc.java:96)
at com.google.cloud.compute.spi.v1.HttpComputeRpc.createInstance(HttpComputeRpc.java:889)
at com.google.cloud.compute.ComputeImpl$61.call(ComputeImpl.java:1664)
at com.google.cloud.compute.ComputeImpl$61.call(ComputeImpl.java:1661)
at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:91)
at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
at com.google.cloud.compute.ComputeImpl.create(ComputeImpl.java:1661)
at jetbrains.buildServer.clouds.google.connector.GoogleApiConnectorImpl$createVmAsync$1.doResume(GoogleApiConnectorImpl.kt:104)
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
"code" : 400,
"errors" : [ {
"domain" : "global",
"message" : "Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network",
"reason" : "invalid"
} ],
"message" : "Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network"
}
at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
at com.google.cloud.compute.spi.v1.HttpComputeRpc.createInstance(HttpComputeRpc.java:887)
... 14 more
```

**Comment by dtretyakov** [comment]
@mayacdoit, thanks for reporting. We need to introduce selector for sub network.

**Comment by dtretyakov** [comment]
@mayacdoit, could you please download the [latest snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityGoogleCloudAgent_Build) to verify, that your case was resolved?

**Comment by mayacdoit** [comment]
Thanks for the quick respond.
I upload the new plugin. But on subnetworks it only let me choose 1 subnetwork although there are 3 subnetworks available. Unfortunately, I needed the one that wasn't showing up.

Thanks,

**Comment by dtretyakov** [comment]
@mayacdoit, could you please ensure that the required [subnet](https://cloud.google.com/vpc/docs/vpc#vpc_networks_and_subnets) is located in the region which was selected for that image? Available subnets in the lists should be from that region.
![image](https://user-images.githubusercontent.com/1025927/33805657-be2b4d0e-ddbc-11e7-9c07-04b9bcfe0ecf.png)
![image](https://user-images.githubusercontent.com/1025927/33805665-dfd466fc-ddbc-11e7-8b0e-b09a53ccb778.png)

**Comment by dtretyakov** [comment]
@mayacdoit, I have fixed possible cause of this issue, so please update the plugin to the [latest snapshot build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityGoogleCloudAgent_Build&guest=1) before check.

**Comment by mayacdoit** [comment]
Now it works better. Good work
But there is another issue. We need to work with gsutil. From the main image there is no issue to run gsutil. From the agents started with teamcity I get: "ServiceException: 401 Anonymous users does not have storage.objects.list access to bucket mybucket"
When launching an image manually gsutil works fine. Digging a bit on the internet didn't help finding a solution.

**Comment by dtretyakov** [comment]
@mayacdoit, thanks for letting me know that use case with subnet selection works fine.

I've created a separate issue for the problem with gsutil: https://github.com/JetBrains/teamcity-google-agent/issues/13
