### ISSUE TITLE
Can't configure profile

### ISSUE THREAD

**Issue by supersteves** [JetBrains/teamcity-google-agent#19]
In logs:

java.lang.NullPointerException
        at com.google.cloud.compute.StorageImageConfiguration$Builder.<init>(StorageImageConfiguration.java:69)
        at com.google.cloud.compute.StorageImageConfiguration$Builder.<init>(StorageImageConfiguration.java:49)
        at com.google.cloud.compute.StorageImageConfiguration.fromPb(StorageImageConfiguration.java:202)
        at com.google.cloud.compute.ImageConfiguration.fromPb(ImageConfiguration.java:188)
        at com.google.cloud.compute.ImageInfo$BuilderImpl.<init>(ImageInfo.java:172)
        at com.google.cloud.compute.Image.fromPb(Image.java:212)
        at com.google.cloud.compute.ComputeImpl$40.apply(ComputeImpl.java:1259)
        at com.google.cloud.compute.ComputeImpl$40.apply(ComputeImpl.java:1256)

I'm also unable to switch between "use machine config" and "json private key" for an already configured profile.

**Comment by supersteves** [comment]
duh, I realise this is the same as https://youtrack.jetbrains.com/issue/TW-53938
