### ISSUE TITLE
Unable to create cloud profile - Invalid disk type URL 

### ISSUE THREAD

**Issue by dhatawesomedude** [JetBrains/teamcity-google-agent#22]
Hi,

I am unable to add new cloud images, or add new cloud profiles for Preemptible instances.
On the cloud profile page, I see the error `https://www.googleapis.com/compute/v1/projects/*****/regions/us-central1/diskTypes/local-ssd is not a valid disk type URL` on the page (screenshot below), and in the logs (`teamcity-clouds.log`), I see the below stacktrace.

Version info
Teamcity - 2017.2.3
Google compute plugin - 0.5.4

This has just popped up recently, I have been able to setup new images and cloud profiles successfully  in the past.

Any Idea how to fix this issue or debug this further is appreciated

![](https://www.evernote.com/shard/s180/sh/012c7a5e-6c2b-47de-931f-6724cac8575e/863c6bb7cd8fe024/res/4d864b6f-fcb3-47e7-9b16-9bafa347ef18/skitch.png?resizeSmall&width=832)
```

[2018-05-25 01:37:25,821]   INFO [io-8111-exec-17] - .google.web.SettingsController - https://www.googleapis.com/compute/v1/projects/*****/regions/us-central1/diskTypes/local-ssd is not a valid disk type URL 
java.lang.IllegalArgumentException: https://www.googleapis.com/compute/v1/projects/*****/regions/us-central1/diskTypes/local-ssd is not a valid disk type URL
        at com.google.cloud.compute.DiskTypeId.fromUrl(DiskTypeId.java:149)
        at com.google.cloud.compute.DiskType.fromPb(DiskType.java:234)
        at com.google.cloud.compute.ComputeImpl$5.apply(ComputeImpl.java:542)
        at com.google.cloud.compute.ComputeImpl$5.apply(ComputeImpl.java:539)
        at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at jetbrains.buildServer.clouds.google.connector.GoogleApiConnectorImpl$getDiskTypesAsync$1.doResume(GoogleApiConnectorImpl.kt:222)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by dtretyakov** [comment]
@dhatawesomedude, could you please try updating the plugin to the latest stable version?

Reference: https://github.com/JetBrains/teamcity-google-agent#installation

**Comment by dhatawesomedude** [comment]
Thanks @dtretyakov. That did the trick. I tried it after I saw the  comment in #7

**Comment by dhatawesomedude** [comment]
Closing this, as updating the plugin has fixed this issue for me.
