### ISSUE TITLE
400 error when starting an instance in a custom subnet: URL is malformed

### ISSUE THREAD

**Issue by jppentti** [JetBrains/teamcity-google-agent#25]
We are trying to create instances in a custom subnetwork and are getting a 400 error from GCP (Stacktrace below). 

According to https://cloud.google.com/compute/docs/reference/rest/v1/instances/updateNetworkInterface the subnetwork value provided should be an URL and from the the stacktrace it looks like the plugin is using the subnetwork `name` property

```com.google.api.gax.rpc.InvalidArgumentException: Bad Requestcom.google.api.gax.rpc.InvalidArgumentException: Bad Request
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90)
at com.google.api.gax.httpjson.HttpJsonExceptionCallable$ExceptionTransformingFuture.onFailure(HttpJsonExceptionCallable.java:106)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:145)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
{
"error": {
"errors": [
{
"domain": "global",
"reason": "invalid",
"message": "Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'tools-network'. The URL is malformed."
}
],
"code": 400,
"message": "Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'tools-network'. The URL is malformed."
}
}

at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1072)
at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:130)
... 7 more```

**Comment by dtretyakov** [comment]
@jppentti, @matti-cujo, it should be fixed in the [latest bug fix update 0.7.2](https://plugins.jetbrains.com/plugin/9704-google-cloud-agents).

**Comment by matti-cujo** [comment]
Indeed, thanks! I closed #26 since your fix is better.
